# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- web_patch

pool:
  vmImage: 'vs2017-win2016'

strategy:
    matrix:
      Python27:
        python.version: '2.7'

steps:
- script: | 
    python -m pip install --upgrade pip
    python -m pip install --upgrade setuptools wheel
    pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    cd PyCybos
    python setup.py sdist bdist_wheel
    cd ../PyXing
    python setup.py sdist bdist_wheel
  displayName: 'Run setup.py'

- script: |
    python -m pip install flake8
    flake8 .
  displayNmae: 'Run lint tests'
