# -*- coding: utf-8 -*-
"""
Created on Wed Jul 24 14:22:24 2013

@author: Administrator
"""

from xing_source import SourceReal

class XAReal_SC3(SourceReal):
    """
    kospi200 stock amend order ack real time receive
    """       
    def __init__(self,shcode=None,DataType='dictionary'):
        super(XAReal_SC3,self).__init__("XA_DataSet.XAReal")
        self.LoadFromResFile("Res\\SC3.res")
        self.shcode = shcode
        self.DataType = DataType   
        pass
    def OnSignal(self):
        if self.DataType == 'dictionary':
            self.data = {}
            self.data['lineseq'] = self.GetFieldData('OutBlock','lineseq')
            self.data['accno'] = self.GetFieldData('OutBlock','accno')
            self.data['user'] = self.GetFieldData('OutBlock','user')
            self.data['len'] = self.GetFieldData('OutBlock','len')
            self.data['gubun'] = self.GetFieldData('OutBlock','gubun')
            self.data['compress'] = self.GetFieldData('OutBlock','compress')
            self.data['encrypt'] = self.GetFieldData('OutBlock','encrypt')
            self.data['offset'] = self.GetFieldData('OutBlock','offset')
            self.data['trcode'] = self.GetFieldData('OutBlock','trcode')
            self.data['compid'] = self.GetFieldData('OutBlock','compid')
            self.data['userid'] = self.GetFieldData('OutBlock','userid')
            self.data['media'] = self.GetFieldData('OutBlock','media')
            self.data['ifid'] = self.GetFieldData('OutBlock','ifid')
            self.data['seq'] = self.GetFieldData('OutBlock','seq')
            self.data['trid'] = self.GetFieldData('OutBlock','trid')
            self.data['pubip'] = self.GetFieldData('OutBlock','pubip')
            self.data['prvip'] = self.GetFieldData('OutBlock','prvip')
            self.data['pcbpno'] = self.GetFieldData('OutBlock','pcbpno')
            self.data['bpno'] = self.GetFieldData('OutBlock','bpno')
            self.data['termno'] = self.GetFieldData('OutBlock','termno')
            self.data['lang'] = self.GetFieldData('OutBlock','lang')
            self.data['proctm'] = self.GetFieldData('OutBlock','proctm')
            self.data['msgcode'] = self.GetFieldData('OutBlock','msgcode')
            self.data['outgu'] = self.GetFieldData('OutBlock','outgu')
            self.data['compreq'] = self.GetFieldData('OutBlock','compreq')
            self.data['funckey'] = self.GetFieldData('OutBlock','funckey')
            self.data['reqcnt'] = self.GetFieldData('OutBlock','reqcnt')
            self.data['filler'] = self.GetFieldData('OutBlock','filler')
            self.data['cont'] = self.GetFieldData('OutBlock','cont')
            self.data['contkey'] = self.GetFieldData('OutBlock','contkey')
            self.data['varlen'] = self.GetFieldData('OutBlock','varlen')
            self.data['varhdlen'] = self.GetFieldData('OutBlock','varhdlen')
            self.data['varmsglen'] = self.GetFieldData('OutBlock','varmsglen')
            self.data['trsrc'] = self.GetFieldData('OutBlock','trsrc')
            self.data['eventid'] = self.GetFieldData('OutBlock','eventid')
            self.data['ifinfo'] = self.GetFieldData('OutBlock','ifinfo')
            self.data['filler1'] = self.GetFieldData('OutBlock','filler1')
            self.data['ordxctptncode'] = self.GetFieldData('OutBlock','ordxctptncode')                
            self.data['ordmktcode'] = self.GetFieldData('OutBlock','ordmktcode')                
            self.data['ordptncode'] = self.GetFieldData('OutBlock','ordptncode')                
            self.data['mgmtbrnno'] = self.GetFieldData('OutBlock','mgmtbrnno')                        
            self.data['accno1'] = self.GetFieldData('OutBlock','accno1')
            self.data['accno2'] = self.GetFieldData('OutBlock','accno2')
            self.data['acntnm'] = self.GetFieldData('OutBlock','acntnm')
            self.data['Isuno'] = self.GetFieldData('OutBlock','Isuno')
            self.data['Isunm'] = self.GetFieldData('OutBlock','Isunm')
            self.data['ordno'] = self.GetFieldData('OutBlock','ordno')
            self.data['orgordno'] = self.GetFieldData('OutBlock','orgordno')
            self.data['execno'] = self.GetFieldData('OutBlock','execno')
            self.data['ordqty'] = self.GetFieldData('OutBlock','ordqty')
            self.data['ordprc'] = self.GetFieldData('OutBlock','ordprc')
            self.data['execqty'] = self.GetFieldData('OutBlock','execqty')
            self.data['execprc'] = self.GetFieldData('OutBlock','execprc')
            self.data['mdfycnfqty'] = self.GetFieldData('OutBlock','mdfycnfqty')
            self.data['mdfycntprc'] = self.GetFieldData('OutBlock','mdfycntprc')
            self.data['canccnfqty'] = self.GetFieldData('OutBlock','canccnfqty')
            self.data['rjtqty'] = self.GetFieldData('OutBlock','rjtqty')
            self.data['ordtrxptncode'] = self.GetFieldData('OutBlock','ordtrxptncode')
            self.data['mtiordseqno'] = self.GetFieldData('OutBlock','mtiordseqno')
            self.data['ordcndi'] = self.GetFieldData('OutBlock','ordcndi')
            self.data['ordprcptncode'] = self.GetFieldData('OutBlock','ordprcptncode')
            self.data['nsavtrdqty'] = self.GetFieldData('OutBlock','nsavtrdqty')
            self.data['shtnIsuno'] = self.GetFieldData('OutBlock','shtnIsuno')
            self.data['opdrtnno'] = self.GetFieldData('OutBlock','opdrtnno')
            self.data['cvrgordtp'] = self.GetFieldData('OutBlock','cvrgordtp')
            self.data['unercqty'] = self.GetFieldData('OutBlock','unercqty')
            self.data['orgordunercqty'] = self.GetFieldData('OutBlock','orgordunercqty')
            self.data['orgordmdftqty'] = self.GetFieldData('OutBlock','orgordmdftqty')
            self.data['orgordcancqty'] = self.GetFieldData('OutBlock','orgordcancqty')
            self.data['ordavrexecprc'] = self.GetFieldData('OutBlock','ordavrexecprc')
            self.data['ordamt'] = self.GetFieldData('OutBlock','ordamt')
            self.data['stdIsuno'] = self.GetFieldData('OutBlock','stdIsuno')
            self.data['bfstdIsuno'] = self.GetFieldData('OutBlock','bfstdIsuno')
            self.data['bnstp'] = self.GetFieldData('OutBlock','bnstp')
            self.data['ordtrdptncode'] = self.GetFieldData('OutBlock','ordtrdptncode')
            self.data['mgntrncode'] = self.GetFieldData('OutBlock','mgntrncode')
            self.data['adduptp'] = self.GetFieldData('OutBlock','adduptp')
            self.data['commdacode'] = self.GetFieldData('OutBlock','commdacode')
            self.data['Loandt'] = self.GetFieldData('OutBlock','Loandt')
            self.data['mbrnmbrno'] = self.GetFieldData('OutBlock','mbrnmbrno')
            self.data['ordacntno'] = self.GetFieldData('OutBlock','ordacntno')
            self.data['agrgbrnno'] = self.GetFieldData('OutBlock','agrgbrnno')
            self.data['mgempno'] = self.GetFieldData('OutBlock','mgempno')
            self.data['futsLnkbrnno'] = self.GetFieldData('OutBlock','futsLnkbrnno')
            self.data['futsLnkacntno'] = self.GetFieldData('OutBlock','futsLnkacntno')
            self.data['futsmkttp'] = self.GetFieldData('OutBlock','futsmkttp')
            self.data['regmktcode'] = self.GetFieldData('OutBlock','regmktcode')
            self.data['mnymgnrat'] = self.GetFieldData('OutBlock','mnymgnrat')
            self.data['substmgnrat'] = self.GetFieldData('OutBlock','substmgnrat')
            self.data['mnyexecamt'] = self.GetFieldData('OutBlock','mnyexecamt')
            self.data['ubstexecamt'] = self.GetFieldData('OutBlock','ubstexecamt')
            self.data['cmsnamtexecamt'] = self.GetFieldData('OutBlock','cmsnamtexecamt')
            self.data['crdtpldgexecamt'] = self.GetFieldData('OutBlock','crdtpldgexecamt')
            self.data['crdtexecamt'] = self.GetFieldData('OutBlock','crdtexecamt')
            self.data['prdayruseexecval'] = self.GetFieldData('OutBlock','prdayruseexecval')
            self.data['crdayruseexecval'] = self.GetFieldData('OutBlock','crdayruseexecval')
            self.data['spotexecqty'] = self.GetFieldData('OutBlock','spotexecqty')
            self.data['stslexecqty'] = self.GetFieldData('OutBlock','stslexecqty')
            self.data['strtgcode'] = self.GetFieldData('OutBlock','strtgcode')
            self.data['grpld'] = self.GetFieldData('OutBlock','grpld')
            self.data['ordseqno'] = self.GetFieldData('OutBlock','ordseqno')
            self.data['ptflno'] = self.GetFieldData('OutBlock','ptflno')
            self.data['bskno'] = self.GetFieldData('OutBlock','bskno')
            self.data['trchno'] = self.GetFieldData('OutBlock','trchno')
            self.data['itemno'] = self.GetFieldData('OutBlock','itemno')
            self.data['orduserId'] = self.GetFieldData('OutBlock','orduserId')
            self.data['brwmgmtYn'] = self.GetFieldData('OutBlock','brwmgmtYn')
            self.data['frgrunqno'] = self.GetFieldData('OutBlock','frgrunqno')
            self.data['trtzxLevytp'] = self.GetFieldData('OutBlock','trtzxLevytp')
            self.data['lptp'] = self.GetFieldData('OutBlock','lptp')
            self.data['exectime'] = self.GetFieldData('OutBlock','exectime')
            self.data['rcptexectime'] = self.GetFieldData('OutBlock','rcptexectime')
            self.data['rmndLoanamt'] = self.GetFieldData('OutBlock','rmndLoanamt')
            self.data['secbalqty'] = self.GetFieldData('OutBlock','secbalqty')
            self.data['spotordableqty'] = self.GetFieldData('OutBlock','spotordableqty')
            self.data['ordableruseqty'] = self.GetFieldData('OutBlock','ordableruseqty')
            self.data['flctqty'] = self.GetFieldData('OutBlock','flctqty')
            self.data['secbalqtyd2'] = self.GetFieldData('OutBlock','secbalqtyd2')
            self.data['sellableqty'] = self.GetFieldData('OutBlock','sellableqty')
            self.data['unercsellordqty'] = self.GetFieldData('OutBlock','unercsellordqty')
            self.data['avrpchsprc'] = self.GetFieldData('OutBlock','avrpchsprc')
            self.data['pchsant'] = self.GetFieldData('OutBlock','pchsant')
            self.data['deposit'] = self.GetFieldData('OutBlock','deposit')
            self.data['substamt'] = self.GetFieldData('OutBlock','substamt')
            self.data['csgnmnymgn'] = self.GetFieldData('OutBlock','csgnmnymgn')
            self.data['csgnsubstmgn'] = self.GetFieldData('OutBlock','csgnsubstmgn')
            self.data['crdtpldgruseamt'] = self.GetFieldData('OutBlock','crdtpldgruseamt')
            self.data['ordablemny'] = self.GetFieldData('OutBlock','ordablemny')
            self.data['ordablesubstamt'] = self.GetFieldData('OutBlock','ordablesubstamt')
            self.data['ruseableamt'] = self.GetFieldData('OutBlock','ruseableamt')
            self.Notify()
        elif self.DataType == 'list':
            self.data = []
            self.data.append(self.GetFieldData('OutBlock','lineseq'))
            self.data.append(self.GetFieldData('OutBlock','accno'))
            self.data.append(self.GetFieldData('OutBlock','user'))
            self.data.append(self.GetFieldData('OutBlock','len'))
            self.data.append(self.GetFieldData('OutBlock','gubun'))
            self.data.append(self.GetFieldData('OutBlock','compress'))
            self.data.append(self.GetFieldData('OutBlock','encrypt'))
            self.data.append(self.GetFieldData('OutBlock','offset'))
            self.data.append(self.GetFieldData('OutBlock','trcode'))
            self.data.append(self.GetFieldData('OutBlock','compid'))
            self.data.append(self.GetFieldData('OutBlock','userid'))
            self.data.append(self.GetFieldData('OutBlock','media'))
            self.data.append(self.GetFieldData('OutBlock','ifid'))
            self.data.append(self.GetFieldData('OutBlock','seq'))
            self.data.append(self.GetFieldData('OutBlock','trid'))
            self.data.append(self.GetFieldData('OutBlock','pubip'))
            self.data.append(self.GetFieldData('OutBlock','prvip'))
            self.data.append(self.GetFieldData('OutBlock','pcbpno'))
            self.data.append(self.GetFieldData('OutBlock','bpno'))
            self.data.append(self.GetFieldData('OutBlock','termno'))
            self.data.append(self.GetFieldData('OutBlock','lang'))
            self.data.append(self.GetFieldData('OutBlock','proctm'))
            self.data.append(self.GetFieldData('OutBlock','msgcode'))
            self.data.append(self.GetFieldData('OutBlock','outgu'))
            self.data.append(self.GetFieldData('OutBlock','compreq'))
            self.data.append(self.GetFieldData('OutBlock','funckey'))
            self.data.append(self.GetFieldData('OutBlock','reqcnt'))
            self.data.append(self.GetFieldData('OutBlock','filler'))
            self.data.append(self.GetFieldData('OutBlock','cont'))
            self.data.append(self.GetFieldData('OutBlock','contkey'))
            self.data.append(self.GetFieldData('OutBlock','varlen'))
            self.data.append(self.GetFieldData('OutBlock','varhdlen'))
            self.data.append(self.GetFieldData('OutBlock','varmsglen'))
            self.data.append(self.GetFieldData('OutBlock','trsrc'))
            self.data.append(self.GetFieldData('OutBlock','eventid'))
            self.data.append(self.GetFieldData('OutBlock','ifinfo'))
            self.data.append(self.GetFieldData('OutBlock','filler1'))
            self.data.append(self.GetFieldData('OutBlock','ordxctptncode'))                
            self.data.append(self.GetFieldData('OutBlock','ordmktcode'))                
            self.data.append(self.GetFieldData('OutBlock','ordptncode'))                
            self.data.append(self.GetFieldData('OutBlock','mgmtbrnno'))                        
            self.data.append(self.GetFieldData('OutBlock','accno1'))
            self.data.append(self.GetFieldData('OutBlock','accno2'))
            self.data.append(self.GetFieldData('OutBlock','acntnm'))
            self.data.append(self.GetFieldData('OutBlock','Isuno'))
            self.data.append(self.GetFieldData('OutBlock','Isunm'))
            self.data.append(self.GetFieldData('OutBlock','ordno'))
            self.data.append(self.GetFieldData('OutBlock','orgordno'))
            self.data.append(self.GetFieldData('OutBlock','execno'))
            self.data.append(self.GetFieldData('OutBlock','ordqty'))
            self.data.append(self.GetFieldData('OutBlock','ordprc'))
            self.data.append(self.GetFieldData('OutBlock','execqty'))
            self.data.append(self.GetFieldData('OutBlock','execprc'))
            self.data.append(self.GetFieldData('OutBlock','mdfycnfqty'))
            self.data.append(self.GetFieldData('OutBlock','mdfycntprc'))
            self.data.append(self.GetFieldData('OutBlock','canccnfqty'))
            self.data.append(self.GetFieldData('OutBlock','rjtqty'))
            self.data.append(self.GetFieldData('OutBlock','ordtrxptncode'))
            self.data.append(self.GetFieldData('OutBlock','mtiordseqno'))
            self.data.append(self.GetFieldData('OutBlock','ordcndi'))
            self.data.append(self.GetFieldData('OutBlock','ordprcptncode'))
            self.data.append(self.GetFieldData('OutBlock','nsavtrdqty'))
            self.data.append(self.GetFieldData('OutBlock','shtnIsuno'))
            self.data.append(self.GetFieldData('OutBlock','opdrtnno'))
            self.data.append(self.GetFieldData('OutBlock','cvrgordtp'))
            self.data.append(self.GetFieldData('OutBlock','unercqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordunercqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordmdftqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordcancqty'))
            self.data.append(self.GetFieldData('OutBlock','ordavrexecprc'))
            self.data.append(self.GetFieldData('OutBlock','ordamt'))
            self.data.append(self.GetFieldData('OutBlock','stdIsuno'))
            self.data.append(self.GetFieldData('OutBlock','bfstdIsuno'))
            self.data.append(self.GetFieldData('OutBlock','bnstp'))
            self.data.append(self.GetFieldData('OutBlock','ordtrdptncode'))
            self.data.append(self.GetFieldData('OutBlock','mgntrncode'))
            self.data.append(self.GetFieldData('OutBlock','adduptp'))
            self.data.append(self.GetFieldData('OutBlock','commdacode'))
            self.data.append(self.GetFieldData('OutBlock','Loandt'))
            self.data.append(self.GetFieldData('OutBlock','mbrnmbrno'))
            self.data.append(self.GetFieldData('OutBlock','ordacntno'))
            self.data.append(self.GetFieldData('OutBlock','agrgbrnno'))
            self.data.append(self.GetFieldData('OutBlock','mgempno'))
            self.data.append(self.GetFieldData('OutBlock','futsLnkbrnno'))
            self.data.append(self.GetFieldData('OutBlock','futsLnkacntno'))
            self.data.append(self.GetFieldData('OutBlock','futsmkttp'))
            self.data.append(self.GetFieldData('OutBlock','regmktcode'))
            self.data.append(self.GetFieldData('OutBlock','mnymgnrat'))
            self.data.append(self.GetFieldData('OutBlock','substmgnrat'))
            self.data.append(self.GetFieldData('OutBlock','mnyexecamt'))
            self.data.append(self.GetFieldData('OutBlock','ubstexecamt'))
            self.data.append(self.GetFieldData('OutBlock','cmsnamtexecamt'))
            self.data.append(self.GetFieldData('OutBlock','crdtpldgexecamt'))
            self.data.append(self.GetFieldData('OutBlock','crdtexecamt'))
            self.data.append(self.GetFieldData('OutBlock','prdayruseexecval'))
            self.data.append(self.GetFieldData('OutBlock','crdayruseexecval'))
            self.data.append(self.GetFieldData('OutBlock','spotexecqty'))
            self.data.append(self.GetFieldData('OutBlock','stslexecqty'))
            self.data.append(self.GetFieldData('OutBlock','strtgcode'))
            self.data.append(self.GetFieldData('OutBlock','grpld'))
            self.data.append(self.GetFieldData('OutBlock','ordseqno'))
            self.data.append(self.GetFieldData('OutBlock','ptflno'))
            self.data.append(self.GetFieldData('OutBlock','bskno'))
            self.data.append(self.GetFieldData('OutBlock','trchno'))
            self.data.append(self.GetFieldData('OutBlock','itemno'))
            self.data.append(self.GetFieldData('OutBlock','orduserId'))
            self.data.append(self.GetFieldData('OutBlock','brwmgmtYn'))
            self.data.append(self.GetFieldData('OutBlock','frgrunqno'))
            self.data.append(self.GetFieldData('OutBlock','trtzxLevytp'))
            self.data.append(self.GetFieldData('OutBlock','lptp'))
            self.data.append(self.GetFieldData('OutBlock','exectime'))
            self.data.append(self.GetFieldData('OutBlock','rcptexectime'))
            self.data.append(self.GetFieldData('OutBlock','rmndLoanamt'))
            self.data.append(self.GetFieldData('OutBlock','secbalqty'))
            self.data.append(self.GetFieldData('OutBlock','spotordableqty'))
            self.data.append(self.GetFieldData('OutBlock','ordableruseqty'))
            self.data.append(self.GetFieldData('OutBlock','flctqty'))
            self.data.append(self.GetFieldData('OutBlock','secbalqtyd2'))
            self.data.append(self.GetFieldData('OutBlock','sellableqty'))
            self.data.append(self.GetFieldData('OutBlock','unercsellordqty'))
            self.data.append(self.GetFieldData('OutBlock','avrpchsprc'))
            self.data.append(self.GetFieldData('OutBlock','pchsant'))
            self.data.append(self.GetFieldData('OutBlock','deposit'))
            self.data.append(self.GetFieldData('OutBlock','substamt'))
            self.data.append(self.GetFieldData('OutBlock','csgnmnymgn'))
            self.data.append(self.GetFieldData('OutBlock','csgnsubstmgn'))
            self.data.append(self.GetFieldData('OutBlock','crdtpldgruseamt'))
            self.data.append(self.GetFieldData('OutBlock','ordablemny'))
            self.data.append(self.GetFieldData('OutBlock','ordablesubstamt'))
            self.data.append(self.GetFieldData('OutBlock','ruseableamt'))
            self.Notify()
        pass