# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcd', models.CharField(max_length=12)),
                ('qty', models.IntegerField()),
                ('mark', models.FloatField()),
                ('tradeprice', models.FloatField()),
                ('pnl_open', models.FloatField()),
            ],
        ),
    ]
