# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqtrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='mark',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='pnl_open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='positions',
            name='tradeprice',
            field=models.FloatField(default=0.0),
        ),
    ]
