# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqtrader', '0002_auto_20200127_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='id',
        ),
        migrations.AlterField(
            model_name='positions',
            name='shortcd',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
