# -*- coding: utf-8 -*-
"""
Created on Tue Jun 24 09:59:21 2014

@author: assa
"""

from xing_source import SourceReal

class XAReal_O01(SourceReal):
    """
    kospi200 futures&options order ack real time receive
    """       
    def __init__(self,shcode=None,DataType='dictionary'):
        super(XAReal_O01,self).__init__("XA_DataSet.XAReal")
        self.LoadFromResFile("Res\\O01.res")
        self.shcode = shcode
        self.DataType = DataType 
        pass
    def OnSignal(self):
        if self.DataType == 'dictionary':
            self.data = {}
            self.data['lineseq'] = self.GetFieldData('OutBlock','lineseq')
            self.data['accno'] = self.GetFieldData('OutBlock','accno')
            self.data['user'] = self.GetFieldData('OutBlock','user')
            self.data['len'] = self.GetFieldData('OutBlock','len')
            self.data['gubun'] = self.GetFieldData('OutBlock','gubun')
            self.data['compress'] = self.GetFieldData('OutBlock','compress')
            self.data['encrypt'] = self.GetFieldData('OutBlock','encrypt')
            self.data['offset'] = self.GetFieldData('OutBlock','offset')
            self.data['trcode'] = self.GetFieldData('OutBlock','trcode')                    
            self.data['compid'] = self.GetFieldData('OutBlock','compid')      
            self.data['userid'] = self.GetFieldData('OutBlock','userid')      
            self.data['media'] = self.GetFieldData('OutBlock','media')      
            self.data['ifid'] = self.GetFieldData('OutBlock','ifid')      
            self.data['seq'] = self.GetFieldData('OutBlock','seq')      
            self.data['trid'] = self.GetFieldData('OutBlock','trid')      
            self.data['pubip'] = self.GetFieldData('OutBlock','pubip')      
            self.data['prvip'] = self.GetFieldData('OutBlock','prvip')      
            self.data['pcbpno'] = self.GetFieldData('OutBlock','pcbpno')      
            self.data['bpno'] = self.GetFieldData('OutBlock','bpno')      
            self.data['termno'] = self.GetFieldData('OutBlock','termno')      
            self.data['lang'] = self.GetFieldData('OutBlock','lang')      
            self.data['proctm'] = self.GetFieldData('OutBlock','proctm')      
            self.data['msgcode'] = self.GetFieldData('OutBlock','msgcode')      
            self.data['outgu'] = self.GetFieldData('OutBlock','outgu')      
            self.data['compreq'] = self.GetFieldData('OutBlock','compreq')      
            self.data['funckey'] = self.GetFieldData('OutBlock','funckey')      
            self.data['reqcnt'] = self.GetFieldData('OutBlock','reqcnt')      
            self.data['filler'] = self.GetFieldData('OutBlock','filler')      
            self.data['cont'] = self.GetFieldData('OutBlock','cont')      
            self.data['contkey'] = self.GetFieldData('OutBlock','contkey')      
            self.data['varlen'] = self.GetFieldData('OutBlock','varlen')      
            self.data['varhdlen'] = self.GetFieldData('OutBlock','varhdlen')      
            self.data['varmsglen'] = self.GetFieldData('OutBlock','varmsglen')      
            self.data['trsrc'] = self.GetFieldData('OutBlock','trsrc')      
            self.data['eventid'] = self.GetFieldData('OutBlock','eventid')      
            self.data['ifinfo'] = self.GetFieldData('OutBlock','ifinfo')      
            self.data['filler1'] = self.GetFieldData('OutBlock','filler1')      
            self.data['trcode1'] = self.GetFieldData('OutBlock','trcode1')    
            self.data['firmno'] = self.GetFieldData('OutBlock','firmno')    
            self.data['acntno'] = self.GetFieldData('OutBlock','acntno')    
            self.data['acntno1'] = self.GetFieldData('OutBlock','acntno1')    
            self.data['acntnm'] = self.GetFieldData('OutBlock','acntnm')    
            self.data['brnno'] = self.GetFieldData('OutBlock','brnno')    
            self.data['ordmktcode'] = self.GetFieldData('OutBlock','ordmktcode')    
            self.data['ordno1'] = self.GetFieldData('OutBlock','ordno1')    
            self.data['ordno'] = self.GetFieldData('OutBlock','ordno')    
            self.data['orgordno'] = self.GetFieldData('OutBlock','orgordno')    
            self.data['prntordno'] = self.GetFieldData('OutBlock','prntordno')    
            self.data['prntordno1'] = self.GetFieldData('OutBlock','prntordno1')    
            self.data['isuno'] = self.GetFieldData('OutBlock','isuno')    
            self.data['fnolsuno'] = self.GetFieldData('OutBlock','fnoIsuno')    
            self.data['fnolsunm'] = self.GetFieldData('OutBlock','fnoIsunm')    
            self.data['pdgrpcode'] = self.GetFieldData('OutBlock','pdgrpcode')    
            self.data['fnoisuptntp'] = self.GetFieldData('OutBlock','fnoisuptntp')    
            self.data['bnstp'] = self.GetFieldData('OutBlock','bnstp')    
            self.data['mrctp'] = self.GetFieldData('OutBlock','mrctp')    
            self.data['ordqty'] = self.GetFieldData('OutBlock','ordqty')    
            self.data['hogatype'] = self.GetFieldData('OutBlock','hogatype')    
            self.data['mmgb'] = self.GetFieldData('OutBlock','mmgb')    
            self.data['ordprc'] = self.GetFieldData('OutBlock','ordprc')    
            self.data['unercqty'] = self.GetFieldData('OutBlock','unercqty')    
            self.data['commdacode'] = self.GetFieldData('OutBlock','commdacode')    
            self.data['peeamtcode'] = self.GetFieldData('OutBlock','peeamtcode')    
            self.data['mgempno'] = self.GetFieldData('OutBlock','mgempno')    
            self.data['fnotrdunitamt'] = self.GetFieldData('OutBlock','fnotrdunitamt')    
            self.data['trxtime'] = self.GetFieldData('OutBlock','trxtime')    
            self.data['strgcode'] = self.GetFieldData('OutBlock','strgcode')    
            self.data['grpId'] = self.GetFieldData('OutBlock','grpId')    
            self.data['ordseqno'] = self.GetFieldData('OutBlock','ordseqno')    
            self.data['ptflno'] = self.GetFieldData('OutBlock','ptflno')    
            self.data['bskno'] = self.GetFieldData('OutBlock','bskno')    
            self.data['trchno'] = self.GetFieldData('OutBlock','trchno')    
            self.data['Itemno'] = self.GetFieldData('OutBlock','Itemno')    
            self.data['userId'] = self.GetFieldData('OutBlock','userId')    
            self.data['opdrtnno'] = self.GetFieldData('OutBlock','opdrtnno')    
            self.data['rjtcode'] = self.GetFieldData('OutBlock','rjtcode')    
            self.data['mrccnfqty'] = self.GetFieldData('OutBlock','mrccnfqty')    
            self.data['orgordunercqty'] = self.GetFieldData('OutBlock','orgordunercqty')    
            self.data['orgordmrcqty'] = self.GetFieldData('OutBlock','orgordmrcqty')    
            self.data['ctrcttime'] = self.GetFieldData('OutBlock','ctrcttime')    
            self.data['ctrctno'] = self.GetFieldData('OutBlock','ctrctno')    
            self.data['execprc'] = self.GetFieldData('OutBlock','execprc')    
            self.data['execqty'] = self.GetFieldData('OutBlock','execqty')    
            self.data['newqty'] = self.GetFieldData('OutBlock','newqty')    
            self.data['qdtqty'] = self.GetFieldData('OutBlock','qdtqty')    
            self.data['lastqty'] = self.GetFieldData('OutBlock','lastqty')    
            self.data['lallexecqty'] = self.GetFieldData('OutBlock','lallexecqty')  
            self.data['allexecamt'] = self.GetFieldData('OutBlock','allexecamt')  
            self.data['fnobalevaltp'] = self.GetFieldData('OutBlock','fnobalevaltp')  
            self.data['bnsplamt'] = self.GetFieldData('OutBlock','bnsplamt')
            self.data['fnoIsuno1'] = self.GetFieldData('OutBlock','fnoIsuno1')  
            self.data['bnstp1'] = self.GetFieldData('OutBlock','bnstp1')  
            self.data['execprc1'] = self.GetFieldData('OutBlock','execprc1')  
            self.data['newqty1'] = self.GetFieldData('OutBlock','newqty1')  
            self.data['qdtqty1'] = self.GetFieldData('OutBlock','qdtqty1')  
            self.data['allexecamt1'] = self.GetFieldData('OutBlock','allexecamt1')  
            self.data['fnoIsuno2'] = self.GetFieldData('OutBlock','fnoIsuno2')  
            self.data['bnstp2'] = self.GetFieldData('OutBlock','bnstp2')  
            self.data['execprc2'] = self.GetFieldData('OutBlock','execprc2')  
            self.data['newqty2'] = self.GetFieldData('OutBlock','newqty2')  
            self.data['lqdtqty2'] = self.GetFieldData('OutBlock','lqdtqty2')  
            self.data['allexecamt2'] = self.GetFieldData('OutBlock','allexecamt2')  
            self.data['dps'] = self.GetFieldData('OutBlock','dps')  
            self.data['ftsubtdsgnamt'] = self.GetFieldData('OutBlock','ftsubtdsgnamt')  
            self.data['mgn'] = self.GetFieldData('OutBlock','mgn')  
            self.data['mnymgn'] = self.GetFieldData('OutBlock','mnymgn')  
            self.data['ordableamt'] = self.GetFieldData('OutBlock','ordableamt')  
            self.data['mnyordableamt'] = self.GetFieldData('OutBlock','mnyordableamt')  
            self.data['fnoIsuno_1'] = self.GetFieldData('OutBlock','fnoIsuno_1')  
            self.data['bnsnp_1'] = self.GetFieldData('OutBlock','bnsnp_1')  
            self.data['unsttqty_1'] = self.GetFieldData('OutBlock','unsttqty_1')  
            self.data['lqdtableqty_1'] = self.GetFieldData('OutBlock','lqdtableqty_1')  
            self.data['avrprc_1'] = self.GetFieldData('OutBlock','avrprc_1')  
            self.data['fnoIsu_2'] = self.GetFieldData('OutBlock','fnoIsu_2')  
            self.data['bnstp_2'] = self.GetFieldData('OutBlock','bnstp_2')  
            self.data['unsttqty_2'] = self.GetFieldData('OutBlock','unsttqty_2')  
            self.data['lqdtableqty_2'] = self.GetFieldData('OutBlock','lqdtableqty_2')  
            self.data['avrprc_2'] = self.GetFieldData('OutBlock','avrprc_2')  
            self.Notify()
        elif self.DataType == 'list':
            self.data = []
            self.data.append(self.GetFieldData('OutBlock','lineseq'))
            self.data.append(self.GetFieldData('OutBlock','accno'))
            self.data.append(self.GetFieldData('OutBlock','user'))
            self.data.append(self.GetFieldData('OutBlock','len'))
            self.data.append(self.GetFieldData('OutBlock','gubun'))
            self.data.append(self.GetFieldData('OutBlock','compress'))
            self.data.append(self.GetFieldData('OutBlock','encrypt'))
            self.data.append(self.GetFieldData('OutBlock','offset'))
            self.data.append(self.GetFieldData('OutBlock','trcode'))
            self.data.append(self.GetFieldData('OutBlock','compid'))
            self.data.append(self.GetFieldData('OutBlock','userid'))
            self.data.append(self.GetFieldData('OutBlock','media'))
            self.data.append(self.GetFieldData('OutBlock','ifid'))
            self.data.append(self.GetFieldData('OutBlock','seq'))
            self.data.append(self.GetFieldData('OutBlock','trid'))
            self.data.append(self.GetFieldData('OutBlock','pubip'))
            self.data.append(self.GetFieldData('OutBlock','prvip'))
            self.data.append(self.GetFieldData('OutBlock','pcbpno'))
            self.data.append(self.GetFieldData('OutBlock','bpno'))
            self.data.append(self.GetFieldData('OutBlock','termno'))
            self.data.append(self.GetFieldData('OutBlock','lang'))
            self.data.append(self.GetFieldData('OutBlock','proctm'))
            self.data.append(self.GetFieldData('OutBlock','msgcode'))
            self.data.append(self.GetFieldData('OutBlock','outgu'))
            self.data.append(self.GetFieldData('OutBlock','compreq'))
            self.data.append(self.GetFieldData('OutBlock','funckey'))
            self.data.append(self.GetFieldData('OutBlock','reqcnt'))
            self.data.append(self.GetFieldData('OutBlock','filler'))
            self.data.append(self.GetFieldData('OutBlock','cont'))
            self.data.append(self.GetFieldData('OutBlock','contkey'))
            self.data.append(self.GetFieldData('OutBlock','varlen'))
            self.data.append(self.GetFieldData('OutBlock','varhdlen'))
            self.data.append(self.GetFieldData('OutBlock','varmsglen'))
            self.data.append(self.GetFieldData('OutBlock','trsrc'))
            self.data.append(self.GetFieldData('OutBlock','eventid'))
            self.data.append(self.GetFieldData('OutBlock','ifinfo'))
            self.data.append(self.GetFieldData('OutBlock','filler1'))
            self.data.append(self.GetFieldData('OutBlock','trcode1'))
            self.data.append(self.GetFieldData('OutBlock','firmno'))
            self.data.append(self.GetFieldData('OutBlock','acntno'))
            self.data.append(self.GetFieldData('OutBlock','acntno1'))
            self.data.append(self.GetFieldData('OutBlock','acntnm'))
            self.data.append(self.GetFieldData('OutBlock','brnno'))
            self.data.append(self.GetFieldData('OutBlock','ordmktcode'))
            self.data.append(self.GetFieldData('OutBlock','ordno1'))
            self.data.append(self.GetFieldData('OutBlock','ordno'))
            self.data.append(self.GetFieldData('OutBlock','orgordno'))
            self.data.append(self.GetFieldData('OutBlock','prntordno'))
            self.data.append(self.GetFieldData('OutBlock','prntordno1'))
            self.data.append(self.GetFieldData('OutBlock','isuno'))
            self.data.append(self.GetFieldData('OutBlock','fnoIsuno'))
            self.data.append(self.GetFieldData('OutBlock','fnoIsunm'))
            self.data.append(self.GetFieldData('OutBlock','pdgrpcode'))
            self.data.append(self.GetFieldData('OutBlock','fnoisuptntp'))
            self.data.append(self.GetFieldData('OutBlock','bnstp'))
            self.data.append(self.GetFieldData('OutBlock','mrctp'))
            self.data.append(self.GetFieldData('OutBlock','ordqty'))
            self.data.append(self.GetFieldData('OutBlock','hogatype'))
            self.data.append(self.GetFieldData('OutBlock','mmgb'))
            self.data.append(self.GetFieldData('OutBlock','ordprc'))
            self.data.append(self.GetFieldData('OutBlock','unercqty'))
            self.data.append(self.GetFieldData('OutBlock','commdacode'))
            self.data.append(self.GetFieldData('OutBlock','peeamtcode'))
            self.data.append(self.GetFieldData('OutBlock','mgempno'))
            self.data.append(self.GetFieldData('OutBlock','fnotrdunitamt'))
            self.data.append(self.GetFieldData('OutBlock','trxtime'))
            self.data.append(self.GetFieldData('OutBlock','strgcode'))
            self.data.append(self.GetFieldData('OutBlock','grpId'))
            self.data.append(self.GetFieldData('OutBlock','ordseqno'))
            self.data.append(self.GetFieldData('OutBlock','ptflno'))
            self.data.append(self.GetFieldData('OutBlock','bskno'))
            self.data.append(self.GetFieldData('OutBlock','trchno'))
            self.data.append(self.GetFieldData('OutBlock','Itemno'))
            self.data.append(self.GetFieldData('OutBlock','userId'))
            self.data.append(self.GetFieldData('OutBlock','opdrtnno'))
            self.data.append(self.GetFieldData('OutBlock','rjtcode'))
            self.data.append(self.GetFieldData('OutBlock','mrccnfqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordunercqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordmrcqty'))
            self.data.append(self.GetFieldData('OutBlock','ctrcttime'))
            self.data.append(self.GetFieldData('OutBlock','ctrctno'))
            self.data.append(self.GetFieldData('OutBlock','execprc'))
            self.data.append(self.GetFieldData('OutBlock','execqty'))
            self.data.append(self.GetFieldData('OutBlock','newqty'))
            self.data.append(self.GetFieldData('OutBlock','qdtqty'))
            self.data.append(self.GetFieldData('OutBlock','lastqty'))
            self.data.append(self.GetFieldData('OutBlock','lallexecqty'))
            self.data.append(self.GetFieldData('OutBlock','allexecamt'))
            self.data.append(self.GetFieldData('OutBlock','fnobalevaltp'))
            self.data.append(self.GetFieldData('OutBlock','bnsplamt'))
            self.data.append(self.GetFieldData('OutBlock','fnoIsuno1'))
            self.data.append(self.GetFieldData('OutBlock','bnstp1'))
            self.data.append(self.GetFieldData('OutBlock','execprc1'))
            self.data.append(self.GetFieldData('OutBlock','newqty1'))
            self.data.append(self.GetFieldData('OutBlock','qdtqty1'))
            self.data.append(self.GetFieldData('OutBlock','allexecamt1'))
            self.data.append(self.GetFieldData('OutBlock','fnoIsuno2'))
            self.data.append(self.GetFieldData('OutBlock','bnstp2'))
            self.data.append(self.GetFieldData('OutBlock','execprc2'))
            self.data.append(self.GetFieldData('OutBlock','newqty2'))
            self.data.append(self.GetFieldData('OutBlock','lqdtqty2'))
            self.data.append(self.GetFieldData('OutBlock','allexecamt2'))
            self.data.append(self.GetFieldData('OutBlock','dps'))
            self.data.append(self.GetFieldData('OutBlock','ftsubtdsgnamt'))
            self.data.append(self.GetFieldData('OutBlock','mgn'))
            self.data.append(self.GetFieldData('OutBlock','mnymgn'))
            self.data.append(self.GetFieldData('OutBlock','ordableamt'))
            self.data.append(self.GetFieldData('OutBlock','mnyordableamt'))
            self.data.append(self.GetFieldData('OutBlock','fnoIsuno_1'))
            self.data.append(self.GetFieldData('OutBlock','bnsnp_1'))
            self.data.append(self.GetFieldData('OutBlock','unsttqty_1'))
            self.data.append(self.GetFieldData('OutBlock','lqdtableqty_1'))
            self.data.append(self.GetFieldData('OutBlock','avrprc_1'))
            self.data.append(self.GetFieldData('OutBlock','fnoIsu_2'))
            self.data.append(self.GetFieldData('OutBlock','bnstp_2'))
            self.data.append(self.GetFieldData('OutBlock','unsttqty_2'))
            self.data.append(self.GetFieldData('OutBlock','lqdtableqty_2'))
            self.data.append(self.GetFieldData('OutBlock','avrprc_2'))            
            self.Notify()
        pass
