# -*- coding: utf-8 -*-
"""
Created on Tue Jul 16 20:11:21 2013

@author: Administrator
"""

from xing_source import SourceReal

class XAReal_H1_(SourceReal):
    """
    kospi200 stock depth tick real time receive
    """
    def __init__(self,shcode=None,DataType='dictionary'):
        super(XAReal_H1_,self).__init__("XA_DataSet.XAReal")
        self.LoadFromResFile("Res\\H1_.res")
        self.shcode = shcode
        self.DataType = DataType  
        pass
    def OnSignal(self):
        if self.DataType == 'dictionary':
            self.data = {}
            self.data['hotime'] = self.GetFieldData('OutBlock','hotime')
            self.data['offerho1'] = self.GetFieldData('OutBlock','offerho1')
            self.data['bidho1'] = self.GetFieldData('OutBlock','bidho1')
            self.data['offerrem1'] = self.GetFieldData('OutBlock','offerrem1')
            self.data['bidrem1'] = self.GetFieldData('OutBlock','bidrem1')        
            self.data['offerho2'] = self.GetFieldData('OutBlock','offerho2')
            self.data['bidho2'] = self.GetFieldData('OutBlock','bidho2')
            self.data['offerrem2'] = self.GetFieldData('OutBlock','offerrem2')
            self.data['bidrem2'] = self.GetFieldData('OutBlock','bidrem2')        
            self.data['offerho3'] = self.GetFieldData('OutBlock','offerho3')
            self.data['bidho3'] = self.GetFieldData('OutBlock','bidho3')
            self.data['offerrem3'] = self.GetFieldData('OutBlock','offerrem3')
            self.data['bidrem3'] = self.GetFieldData('OutBlock','bidrem3')        
            self.data['offerho4'] = self.GetFieldData('OutBlock','offerho4')
            self.data['bidho4'] = self.GetFieldData('OutBlock','bidho4')
            self.data['offerrem4'] = self.GetFieldData('OutBlock','offerrem4')
            self.data['bidrem4'] = self.GetFieldData('OutBlock','bidrem4')        
            self.data['offerho5'] = self.GetFieldData('OutBlock','offerho5')
            self.data['bidho5'] = self.GetFieldData('OutBlock','bidho5')
            self.data['offerrem5'] = self.GetFieldData('OutBlock','offerrem5')
            self.data['bidrem5'] = self.GetFieldData('OutBlock','bidrem5')
            self.data['offerho6'] = self.GetFieldData('OutBlock','offerho6')
            self.data['bidho6'] = self.GetFieldData('OutBlock','bidho6')
            self.data['offerrem6'] = self.GetFieldData('OutBlock','offerrem6')
            self.data['bidrem6'] = self.GetFieldData('OutBlock','bidrem6')
            self.data['offerho7'] = self.GetFieldData('OutBlock','offerho7')
            self.data['bidho7'] = self.GetFieldData('OutBlock','bidho7')
            self.data['offerrem7'] = self.GetFieldData('OutBlock','offerrem7')
            self.data['bidrem7'] = self.GetFieldData('OutBlock','bidrem7')
            self.data['offerho8'] = self.GetFieldData('OutBlock','offerho8')
            self.data['bidho8'] = self.GetFieldData('OutBlock','bidho8')
            self.data['offerrem8'] = self.GetFieldData('OutBlock','offerrem8')
            self.data['bidrem8'] = self.GetFieldData('OutBlock','bidrem8')
            self.data['offerho7'] = self.GetFieldData('OutBlock','offerho7')
            self.data['bidho7'] = self.GetFieldData('OutBlock','bidho7')
            self.data['offerrem7'] = self.GetFieldData('OutBlock','offerrem7')
            self.data['bidrem7'] = self.GetFieldData('OutBlock','bidrem7')
            self.data['offerho8'] = self.GetFieldData('OutBlock','offerho8')
            self.data['bidho8'] = self.GetFieldData('OutBlock','bidho8')
            self.data['offerrem8'] = self.GetFieldData('OutBlock','offerrem8')
            self.data['bidrem8'] = self.GetFieldData('OutBlock','bidrem8')
            self.data['offerho9'] = self.GetFieldData('OutBlock','offerho9')
            self.data['bidho9'] = self.GetFieldData('OutBlock','bidho9')
            self.data['offerrem9'] = self.GetFieldData('OutBlock','offerrem9')
            self.data['bidrem9'] = self.GetFieldData('OutBlock','bidrem9')
            self.data['offerho10'] = self.GetFieldData('OutBlock','offerho10')
            self.data['bidho10'] = self.GetFieldData('OutBlock','bidho10')
            self.data['offerrem10'] = self.GetFieldData('OutBlock','offerrem10')
            self.data['bidrem10'] = self.GetFieldData('OutBlock','bidrem10')
            self.data['totofferrem'] = self.GetFieldData('OutBlock','totofferrem')
            self.data['totbidrem'] = self.GetFieldData('OutBlock','totbidrem')        
            self.data['donsigubun'] = self.GetFieldData('OutBlock','donsigubun')
            self.data['shcode'] = self.GetFieldData('OutBlock','shcode')        
            self.Notify()
        elif self.DataType == 'list':
            self.data = []
            self.data.append(self.GetFieldData('OutBlock','hotime'))
            self.data.append(self.GetFieldData('OutBlock','offerho1'))
            self.data.append(self.GetFieldData('OutBlock','bidho1'))
            self.data.append(self.GetFieldData('OutBlock','offerrem1'))
            self.data.append(self.GetFieldData('OutBlock','bidrem1'))        
            self.data.append(self.GetFieldData('OutBlock','offerho2'))
            self.data.append(self.GetFieldData('OutBlock','bidho2'))
            self.data.append(self.GetFieldData('OutBlock','offerrem2'))
            self.data.append(self.GetFieldData('OutBlock','bidrem2'))        
            self.data.append(self.GetFieldData('OutBlock','offerho3'))
            self.data.append(self.GetFieldData('OutBlock','bidho3'))
            self.data.append(self.GetFieldData('OutBlock','offerrem3'))
            self.data.append(self.GetFieldData('OutBlock','bidrem3'))        
            self.data.append(self.GetFieldData('OutBlock','offerho4'))
            self.data.append(self.GetFieldData('OutBlock','bidho4'))
            self.data.append(self.GetFieldData('OutBlock','offerrem4'))
            self.data.append(self.GetFieldData('OutBlock','bidrem4'))        
            self.data.append(self.GetFieldData('OutBlock','offerho5'))
            self.data.append(self.GetFieldData('OutBlock','bidho5'))
            self.data.append(self.GetFieldData('OutBlock','offerrem5'))
            self.data.append(self.GetFieldData('OutBlock','bidrem5'))
            self.data.append(self.GetFieldData('OutBlock','offerho6'))
            self.data.append(self.GetFieldData('OutBlock','bidho6'))
            self.data.append(self.GetFieldData('OutBlock','offerrem6'))
            self.data.append(self.GetFieldData('OutBlock','bidrem6'))
            self.data.append(self.GetFieldData('OutBlock','offerho7'))
            self.data.append(self.GetFieldData('OutBlock','bidho7'))
            self.data.append(self.GetFieldData('OutBlock','offerrem7'))
            self.data.append(self.GetFieldData('OutBlock','bidrem7'))
            self.data.append(self.GetFieldData('OutBlock','offerho8'))
            self.data.append(self.GetFieldData('OutBlock','bidho8'))
            self.data.append(self.GetFieldData('OutBlock','offerrem8'))
            self.data.append(self.GetFieldData('OutBlock','bidrem8'))
            self.data.append(self.GetFieldData('OutBlock','offerho7'))
            self.data.append(self.GetFieldData('OutBlock','bidho7'))
            self.data.append(self.GetFieldData('OutBlock','offerrem7'))
            self.data.append(self.GetFieldData('OutBlock','bidrem7'))
            self.data.append(self.GetFieldData('OutBlock','offerho8'))
            self.data.append(self.GetFieldData('OutBlock','bidho8'))
            self.data.append(self.GetFieldData('OutBlock','offerrem8'))
            self.data.append(self.GetFieldData('OutBlock','bidrem8'))
            self.data.append(self.GetFieldData('OutBlock','offerho9'))
            self.data.append(self.GetFieldData('OutBlock','bidho9'))
            self.data.append(self.GetFieldData('OutBlock','offerrem9'))
            self.data.append(self.GetFieldData('OutBlock','bidrem9'))
            self.data.append(self.GetFieldData('OutBlock','offerho10'))
            self.data.append(self.GetFieldData('OutBlock','bidho10'))
            self.data.append(self.GetFieldData('OutBlock','offerrem10'))
            self.data.append(self.GetFieldData('OutBlock','bidrem10'))
            self.data.append(self.GetFieldData('OutBlock','totofferrem'))
            self.data.append(self.GetFieldData('OutBlock','totbidrem'))        
            self.data.append(self.GetFieldData('OutBlock','donsigubun'))
            self.data.append(self.GetFieldData('OutBlock','shcode'))        
            self.Notify()
        pass