# -*- coding: utf-8 -*-
"""
Created on Tue Jul 23 10:33:22 2013

@author: Administrator
"""

from xing_source import SourceReal

class XAReal_SC0(SourceReal):
    """
    kospi200 stock normal order ack real time receive
    """       
    def __init__(self,shcode=None,DataType='dictionary'):
        super(XAReal_SC0,self).__init__("XA_DataSet.XAReal")
        self.LoadFromResFile("Res\\SC0.res")
        self.shcode = shcode
        self.DataType = DataType     
        #self.SetFieldData('InBlock')
        pass
    def OnSignal(self):
        if self.DataType == 'dictionary':
            self.data = {}
            self.data['lineseq'] = self.GetFieldData('OutBlock','lineseq')
            self.data['accno'] = self.GetFieldData('OutBlock','accno')
            self.data['user'] = self.GetFieldData('OutBlock','user')
            self.data['len'] = self.GetFieldData('OutBlock','len')
            self.data['gubun'] = self.GetFieldData('OutBlock','gubun')
            self.data['compress'] = self.GetFieldData('OutBlock','compress')
            self.data['encrypt'] = self.GetFieldData('OutBlock','encrypt')
            self.data['offset'] = self.GetFieldData('OutBlock','offset')
            self.data['trcode'] = self.GetFieldData('OutBlock','trcode')
            self.data['compid'] = self.GetFieldData('OutBlock','compid')
            self.data['userid'] = self.GetFieldData('OutBlock','userid')
            self.data['media'] = self.GetFieldData('OutBlock','media')
            self.data['ifid'] = self.GetFieldData('OutBlock','ifid')
            self.data['seq'] = self.GetFieldData('OutBlock','seq')
            self.data['trid'] = self.GetFieldData('OutBlock','trid')
            self.data['pubip'] = self.GetFieldData('OutBlock','pubip')
            self.data['prvip'] = self.GetFieldData('OutBlock','prvip')
            self.data['pcbpno'] = self.GetFieldData('OutBlock','pcbpno')
            self.data['bpno'] = self.GetFieldData('OutBlock','bpno')
            self.data['termno'] = self.GetFieldData('OutBlock','termno')
            self.data['lang'] = self.GetFieldData('OutBlock','lang')
            self.data['proctm'] = self.GetFieldData('OutBlock','proctm')
            self.data['msgcode'] = self.GetFieldData('OutBlock','msgcode')
            self.data['outgu'] = self.GetFieldData('OutBlock','outgu')
            self.data['compreq'] = self.GetFieldData('OutBlock','compreq')
            self.data['funckey'] = self.GetFieldData('OutBlock','funckey')
            self.data['reqcnt'] = self.GetFieldData('OutBlock','reqcnt')
            self.data['filler'] = self.GetFieldData('OutBlock','filler')
            self.data['cont'] = self.GetFieldData('OutBlock','cont')
            self.data['contkey'] = self.GetFieldData('OutBlock','contkey')
            self.data['varlen'] = self.GetFieldData('OutBlock','varlen')
            self.data['varhdlen'] = self.GetFieldData('OutBlock','varhdlen')
            self.data['varmsglen'] = self.GetFieldData('OutBlock','varmsglen')
            self.data['trsrc'] = self.GetFieldData('OutBlock','trsrc')
            self.data['eventid'] = self.GetFieldData('OutBlock','eventid')
            self.data['ifinfo'] = self.GetFieldData('OutBlock','ifinfo')
            self.data['filler1'] = self.GetFieldData('OutBlock','filler1')
            self.data['ordchegb'] = self.GetFieldData('OutBlock','ordchegb')
            self.data['marketgb'] = self.GetFieldData('OutBlock','marketgb')
            self.data['ordgb'] = self.GetFieldData('OutBlock','ordgb')
            self.data['orgordno'] = self.GetFieldData('OutBlock','orgordno')
            self.data['accno1'] = self.GetFieldData('OutBlock','accno1')
            self.data['accno2'] = self.GetFieldData('OutBlock','accno2')
            self.data['passwd'] = self.GetFieldData('OutBlock','passwd')
            self.data['expcode'] = self.GetFieldData('OutBlock','expcode')
            self.data['shtcode'] = self.GetFieldData('OutBlock','shtcode')
            self.data['hname'] = self.GetFieldData('OutBlock','hname')
            self.data['ordqty'] = self.GetFieldData('OutBlock','ordqty')
            self.data['ordprice'] = self.GetFieldData('OutBlock','ordprice')
            self.data['hogagb'] = self.GetFieldData('OutBlock','hogagb')
            self.data['etfhogagb'] = self.GetFieldData('OutBlock','etfhogagb')
            self.data['pgmtype'] = self.GetFieldData('OutBlock','pgmtype')
            self.data['gmhogagb'] = self.GetFieldData('OutBlock','gmhogagb')
            self.data['gmhogayn'] = self.GetFieldData('OutBlock','gmhogayn')
            self.data['singb'] = self.GetFieldData('OutBlock','singb')
            self.data['loandt'] = self.GetFieldData('OutBlock','loandt')
            self.data['cvrgordtp'] = self.GetFieldData('OutBlock','cvrgordtp')
            self.data['strtgcode'] = self.GetFieldData('OutBlock','strtgcode')
            self.data['groupid'] = self.GetFieldData('OutBlock','groupid')
            self.data['ordseqno'] = self.GetFieldData('OutBlock','ordseqno')
            self.data['prtno'] = self.GetFieldData('OutBlock','prtno')
            self.data['basketno'] = self.GetFieldData('OutBlock','basketno')
            self.data['trchno'] = self.GetFieldData('OutBlock','trchno')
            self.data['itemno'] = self.GetFieldData('OutBlock','itemno')
            self.data['brwmgmyn'] = self.GetFieldData('OutBlock','brwmgmyn')
            self.data['mbrno'] = self.GetFieldData('OutBlock','mbrno')
            self.data['procgb'] = self.GetFieldData('OutBlock','procgb')
            self.data['admbrchno'] = self.GetFieldData('OutBlock','admbrchno')
            self.data['futaccno'] = self.GetFieldData('OutBlock','futaccno')
            self.data['futmarketgb'] = self.GetFieldData('OutBlock','futmarketgb')
            self.data['tongsingb'] = self.GetFieldData('OutBlock','tongsingb')
            self.data['lpgb'] = self.GetFieldData('OutBlock','lpgb')
            self.data['dummy'] = self.GetFieldData('OutBlock','dummy')
            self.data['ordno'] = self.GetFieldData('OutBlock','ordno')
            self.data['ordtm'] = self.GetFieldData('OutBlock','ordtm')
            self.data['prntordno'] = self.GetFieldData('OutBlock','prntordno')
            self.data['mgempno'] = self.GetFieldData('OutBlock','mgempno')
            self.data['orgordundrqty'] = self.GetFieldData('OutBlock','orgordundrqty')
            self.data['orgordmdfyqty'] = self.GetFieldData('OutBlock','orgordmdfyqty')
            self.data['orgordcancelqty'] = self.GetFieldData('OutBlock','orgordcancelqty')
            self.data['nmcpysndno'] = self.GetFieldData('OutBlock','nmcpysndno')
            self.data['ordamt'] = self.GetFieldData('OutBlock','ordamt')
            self.data['bnstp'] = self.GetFieldData('OutBlock','bnstp')
            self.data['spareordno'] = self.GetFieldData('OutBlock','spareordno')
            self.data['cvrgseqno'] = self.GetFieldData('OutBlock','cvrgseqno')
            self.data['rsvordno'] = self.GetFieldData('OutBlock','rsvordno')
            self.data['mtordseqno'] = self.GetFieldData('OutBlock','mtordseqno')
            self.data['spotordqty'] = self.GetFieldData('OutBlock','spotordqty')
            self.data['orduseqty'] = self.GetFieldData('OutBlock','orduseqty')
            self.data['mnyordamt'] = self.GetFieldData('OutBlock','mnyordamt')
            self.data['ordsubstamt'] = self.GetFieldData('OutBlock','ordsubstamt')
            self.data['ruseordamt'] = self.GetFieldData('OutBlock','ruseordamt')
            self.data['ordcmsnamt'] = self.GetFieldData('OutBlock','ordcmsnamt')
            self.data['crdtuseamt'] = self.GetFieldData('OutBlock','crdtuseamt')
            self.data['secbalqty'] = self.GetFieldData('OutBlock','secbalqty')
            self.data['spotordableqty'] = self.GetFieldData('OutBlock','spotordableqty')
            self.data['ordableruseqty'] = self.GetFieldData('OutBlock','ordableruseqty')
            self.data['flctqty'] = self.GetFieldData('OutBlock','flctqty')
            self.data['secbalqtyd2'] = self.GetFieldData('OutBlock','secbalqtyd2')
            self.data['sellableqty'] = self.GetFieldData('OutBlock','sellableqty')
            self.data['unercsellordqty'] = self.GetFieldData('OutBlock','unercsellordqty')
            self.data['avrpchsprc'] = self.GetFieldData('OutBlock','avrpchsprc')
            self.data['pchsamt'] = self.GetFieldData('OutBlock','pchsamt')
            self.data['deposit'] = self.GetFieldData('OutBlock','deposit')
            self.data['substamt'] = self.GetFieldData('OutBlock','substamt')
            self.data['csgnmnygn'] = self.GetFieldData('OutBlock','csgnmnygn')
            self.data['csgnsubstmgn'] = self.GetFieldData('OutBlock','csgnsubstmgn')
            self.data['crdtpldgruseamt'] = self.GetFieldData('OutBlock','crdtpldgruseamt')
            self.data['ordablemny'] = self.GetFieldData('OutBlock','ordablemny')
            self.data['ordablesubstamt'] = self.GetFieldData('OutBlock','ordablesubstamt')
            self.data['ruseableamt'] = self.GetFieldData('OutBlock','ruseableamt')
            self.Notify()
        elif self.DataType == 'list':
            self.data = []
            self.data.append(self.GetFieldData('OutBlock','lineseq'))
            self.data.append(self.GetFieldData('OutBlock','accno'))
            self.data.append(self.GetFieldData('OutBlock','user'))
            self.data.append(self.GetFieldData('OutBlock','len'))
            self.data.append(self.GetFieldData('OutBlock','gubun'))
            self.data.append(self.GetFieldData('OutBlock','compress'))
            self.data.append(self.GetFieldData('OutBlock','encrypt'))
            self.data.append(self.GetFieldData('OutBlock','offset'))
            self.data.append(self.GetFieldData('OutBlock','trcode'))
            self.data.append(self.GetFieldData('OutBlock','compid'))
            self.data.append(self.GetFieldData('OutBlock','userid'))
            self.data.append(self.GetFieldData('OutBlock','media'))
            self.data.append(self.GetFieldData('OutBlock','ifid'))
            self.data.append(self.GetFieldData('OutBlock','seq'))
            self.data.append(self.GetFieldData('OutBlock','trid'))
            self.data.append(self.GetFieldData('OutBlock','pubip'))
            self.data.append(self.GetFieldData('OutBlock','prvip'))
            self.data.append(self.GetFieldData('OutBlock','pcbpno'))
            self.data.append(self.GetFieldData('OutBlock','bpno'))
            self.data.append(self.GetFieldData('OutBlock','termno'))
            self.data.append(self.GetFieldData('OutBlock','lang'))
            self.data.append(self.GetFieldData('OutBlock','proctm'))
            self.data.append(self.GetFieldData('OutBlock','msgcode'))
            self.data.append(self.GetFieldData('OutBlock','outgu'))
            self.data.append(self.GetFieldData('OutBlock','compreq'))
            self.data.append(self.GetFieldData('OutBlock','funckey'))
            self.data.append(self.GetFieldData('OutBlock','reqcnt'))
            self.data.append(self.GetFieldData('OutBlock','filler'))
            self.data.append(self.GetFieldData('OutBlock','cont'))
            self.data.append(self.GetFieldData('OutBlock','contkey'))
            self.data.append(self.GetFieldData('OutBlock','varlen'))
            self.data.append(self.GetFieldData('OutBlock','varhdlen'))
            self.data.append(self.GetFieldData('OutBlock','varmsglen'))
            self.data.append(self.GetFieldData('OutBlock','trsrc'))
            self.data.append(self.GetFieldData('OutBlock','eventid'))
            self.data.append(self.GetFieldData('OutBlock','ifinfo'))
            self.data.append(self.GetFieldData('OutBlock','filler1'))
            self.data.append(self.GetFieldData('OutBlock','ordchegb'))
            self.data.append(self.GetFieldData('OutBlock','marketgb'))
            self.data.append(self.GetFieldData('OutBlock','ordgb'))
            self.data.append(self.GetFieldData('OutBlock','orgordno'))
            self.data.append(self.GetFieldData('OutBlock','accno1'))
            self.data.append(self.GetFieldData('OutBlock','accno2'))
            self.data.append(self.GetFieldData('OutBlock','passwd'))
            self.data.append(self.GetFieldData('OutBlock','expcode'))
            self.data.append(self.GetFieldData('OutBlock','shtcode'))
            self.data.append(self.GetFieldData('OutBlock','hname'))
            self.data.append(self.GetFieldData('OutBlock','ordqty'))
            self.data.append(self.GetFieldData('OutBlock','ordprice'))
            self.data.append(self.GetFieldData('OutBlock','hogagb'))
            self.data.append(self.GetFieldData('OutBlock','etfhogagb'))
            self.data.append(self.GetFieldData('OutBlock','pgmtype'))
            self.data.append(self.GetFieldData('OutBlock','gmhogagb'))
            self.data.append(self.GetFieldData('OutBlock','gmhogayn'))
            self.data.append(self.GetFieldData('OutBlock','singb'))
            self.data.append(self.GetFieldData('OutBlock','loandt'))
            self.data.append(self.GetFieldData('OutBlock','cvrgordtp'))
            self.data.append(self.GetFieldData('OutBlock','strtgcode'))
            self.data.append(self.GetFieldData('OutBlock','groupid'))
            self.data.append(self.GetFieldData('OutBlock','ordseqno'))
            self.data.append(self.GetFieldData('OutBlock','prtno'))
            self.data.append(self.GetFieldData('OutBlock','basketno'))
            self.data.append(self.GetFieldData('OutBlock','trchno'))
            self.data.append(self.GetFieldData('OutBlock','itemno'))
            self.data.append(self.GetFieldData('OutBlock','brwmgmyn'))
            self.data.append(self.GetFieldData('OutBlock','mbrno'))
            self.data.append(self.GetFieldData('OutBlock','procgb'))
            self.data.append(self.GetFieldData('OutBlock','admbrchno'))
            self.data.append(self.GetFieldData('OutBlock','futaccno'))
            self.data.append(self.GetFieldData('OutBlock','futmarketgb'))
            self.data.append(self.GetFieldData('OutBlock','tongsingb'))
            self.data.append(self.GetFieldData('OutBlock','lpgb'))
            self.data.append(self.GetFieldData('OutBlock','dummy'))
            self.data.append(self.GetFieldData('OutBlock','ordno'))            
            self.data.append(self.GetFieldData('OutBlock','ordtm'))
            self.data.append(self.GetFieldData('OutBlock','prntordno'))            
            self.data.append(self.GetFieldData('OutBlock','mgempno'))
            self.data.append(self.GetFieldData('OutBlock','orgordundrqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordmdfyqty'))
            self.data.append(self.GetFieldData('OutBlock','orgordcancelqty'))
            self.data.append(self.GetFieldData('OutBlock','nmcpysndno'))
            self.data.append(self.GetFieldData('OutBlock','ordamt'))
            self.data.append(self.GetFieldData('OutBlock','bnstp'))
            self.data.append(self.GetFieldData('OutBlock','spareordno'))        
            self.data.append(self.GetFieldData('OutBlock','cvrgseqno'))
            self.data.append(self.GetFieldData('OutBlock','rsvordno'))            
            self.data.append(self.GetFieldData('OutBlock','mtordseqno'))
            self.data.append(self.GetFieldData('OutBlock','spotordqty'))
            self.data.append(self.GetFieldData('OutBlock','orduseqty'))
            self.data.append(self.GetFieldData('OutBlock','mnyordamt'))
            self.data.append(self.GetFieldData('OutBlock','ordsubstamt'))
            self.data.append(self.GetFieldData('OutBlock','ruseordamt'))
            self.data.append(self.GetFieldData('OutBlock','ordcmsnamt'))
            self.data.append(self.GetFieldData('OutBlock','crdtuseamt'))
            self.data.append(self.GetFieldData('OutBlock','secbalqty'))
            self.data.append(self.GetFieldData('OutBlock','spotordableqty'))
            self.data.append(self.GetFieldData('OutBlock','ordableruseqty'))
            self.data.append(self.GetFieldData('OutBlock','flctqty'))
            self.data.append(self.GetFieldData('OutBlock','secbalqtyd2'))
            self.data.append(self.GetFieldData('OutBlock','sellableqty'))
            self.data.append(self.GetFieldData('OutBlock','unercsellordqty'))
            self.data.append(self.GetFieldData('OutBlock','avrpchsprc'))
            self.data.append(self.GetFieldData('OutBlock','pchsamt'))
            self.data.append(self.GetFieldData('OutBlock','deposit'))
            self.data.append(self.GetFieldData('OutBlock','substamt'))
            self.data.append(self.GetFieldData('OutBlock','csgnmnygn'))
            self.data.append(self.GetFieldData('OutBlock','csgnsubstmgn'))
            self.data.append(self.GetFieldData('OutBlock','crdtpldgruseamt'))
            self.data.append(self.GetFieldData('OutBlock','ordablemny'))
            self.data.append(self.GetFieldData('OutBlock','ordablesubstamt'))
            self.data.append(self.GetFieldData('OutBlock','ruseableamt'))
            self.Notify()
        pass
    
        
        
        
        